services:
    devpisrv:
        image: muccg/devpi:latest
        volumes:
         - devpisrv-data:/data
        user: "${UID}:${GID}"
        ports:
         - 3141:3141
        environment:
         - DEVPI_PASSWORD=
        restart: always
        #profiles:
        # - donotstart

    apt_cacher_ng:
        image: sameersbn/apt-cacher-ng:3.7.4-20220421
        ports:
         - 3142:3142
        volumes:
         - apt-cacher-ng:/var/cache/apt-cacher-ng
        restart: always
        #profiles:
        # - donotstart
    portainer:
        image: portainer/portainer-ce
        container_name: portainer
        restart: always
        ports:
        - "9000:9000"
        # expose:
        # - "9000"
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

    nginx_proxy:
        image: nginx:stable
        container_name: nginx-https-proxy
        restart: unless-stopped
        volumes:
        - ../volumes/nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
        - ../volumes/nginx_config/options-ssl-nginx.conf:/etc/nginx/options-ssl-nginx.conf:ro
        - ../volumes/nginx_config/ssl-dhparams.pem:/etc/nginx/ssl-dhparams.pem:ro
        # # - ./nginx/htpasswd:/etc/nginx/htpasswd:ro
        - /etc/lfmsh.online:/etc/lfmsh.online:ro
        ports:
        - "443:443"
        network_mode: host

volumes:

  devpisrv-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/devpisrv-data'

  apt-cacher-ng:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/apt-cacher-ng'

  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/portainer_data'


