services:
    devpisrv:
        build: /home/abulatov/Projects/lfmsh-admin/computer-class-server/pypimirror
        ports:
         - "${SERVER_IP:-0.0.0.0}:${DEVPISRV_PORT:-3141}:3141"
        volumes:
         - devpisrv-data:/var/local/devpisrv
        restart: always
        #profiles:
        # - donotstart

    openldap:
        image: docker.io/bitnami/openldap:2.6
        ports:
         - '389:1389'
         - '636:1636'
        environment:
         - LDAP_ADMIN_USERNAME=admin
         - LDAP_ADMIN_PASSWORD=adminpassword
         - LDAP_USERS=user01,user02
         - LDAP_PASSWORDS=password1,password2
        volumes:
         - 'openldap-data:/bitnami/openldap'

    phpldapadmin:
        image: osixia/phpldapadmin:0.9.0
        ports:
         - '6443:443'
        environment:
         - PHPLDAPADMIN_LDAP_HOSTS=${SERVER_IP}
         #- PHPLDAPADMIN_HTTPS=false
        restart: always

    apt_cacher_ng:
        image: sameersbn/apt-cacher-ng:3.7.4-20220421
        ports:
         - 3142:3142
        volumes:
         - apt-cacher-ng:/var/cache/apt-cacher-ng


volumes:
  openldap-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/openldap-data'

  devpisrv-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/devpisrv-data'

  apt-cacher-ng:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/apt-cacher-ng'


