services:
    devpisrv:
        image: muccg/devpi:latest
        volumes:
         - devpisrv-data:/data
        ports:
         - 3141:3141
        environment:
         - DEVPI_PASSWORD=
        restart: always
        #profiles:
        # - donotstart

    openldap:
        image: docker.io/bitnami/openldap:2.6
        ports:
         - '389:1389'
         - '636:1636'
        environment:
         - LDAP_ADMIN_USERNAME=${LDAP_ADMIN_USERNAME}
         - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
         - LDAP_USERS=user01,user02
         - LDAP_PASSWORDS=password1,password2
        volumes:
         - 'openldap-data:/bitnami/openldap'
        restart: always
        profiles:
         - donotstart

    phpldapadmin:
        image: osixia/phpldapadmin:0.9.0
        ports:
         - '6443:443'
        environment:
         - PHPLDAPADMIN_LDAP_HOSTS=${SERVER_IP}
         #- PHPLDAPADMIN_HTTPS=false
        restart: always
        profiles:
         - donotstart

    apt_cacher_ng:
        image: sameersbn/apt-cacher-ng:3.7.4-20220421
        ports:
         - 3142:3142
        volumes:
         - apt-cacher-ng:/var/cache/apt-cacher-ng
        restart: always
        profiles:
         - donotstart


volumes:
  openldap-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/openldap-data'

  devpisrv-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/devpisrv-data'

  apt-cacher-ng:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../volumes/apt-cacher-ng'


